-- Migration: Create sholat_reports table
CREATE TABLE IF NOT EXISTS sholat_reports (
  id SERIAL PRIMARY KEY,
  siswa_id INTEGER NOT NULL REFERENCES siswa(id) ON DELETE CASCADE,
  tanggal DATE NOT NULL,
  subuh BOOLEAN NOT NULL DEFAULT FALSE,
  dzuhur BOOLEAN NOT NULL DEFAULT FALSE,
  ashar BOOLEAN NOT NULL DEFAULT FALSE,
  maghrib BOOLEAN NOT NULL DEFAULT FALSE,
  isya BOOLEAN NOT NULL DEFAULT FALSE,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (siswa_id, tanggal)
);
